---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0
  - name: fedora-21

suites:
  - name: package
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: package
  - name: source
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: source
  - name: ppa
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: ppa
    excludes:
      - centos-6.6
      - centos-7.0
      - fedora-21
  - name: consul
    run_list:
      - recipe[my-consul-lb]
    excludes:
      - ubuntu-12.04
      - ubuntu-14.04
      - centos-6.6
      - fedora-21
